pipelines:
  default:
    - step:
        name: Build SourcePawn Scripts
        image: debian:buster
        caches:
          - sourcemod
        script:
          - apt-get update && apt-get install -y lib32stdc++6 wget
          - bash getbuildtools.sh
          - cp -rv scripting/* addons/sourcemod/scripting/
          - mkdir -p addons/sourcemod/translations && cp -rv translations/* addons/sourcemod/translations/
          - bash addons/sourcemod/scripting/compile.sh
        artifacts:
          - addons/sourcemod/scripting/compiled/*.smx
          - addons/sourcemod/translations/*.txt
    - step:
        name: Generate Payload
        image: debian:buster
        script:
          - tar -zcvf compiled.tar.gz addons/sourcemod/scripting/compiled/*.smx  addons/sourcemod/translations/*.txt
        artifacts:
          - compiled.tar.gz

definitions:
  caches:
    sourcemod: addons
